### ISSUE TITLE
DONE message should include output file

### ISSUE THREAD

**Issue by edsu** [sul-dlss/speech-to-text#21]
Blocked by #3

When a speech-to-text job finishes successfully a message is put into the DONE SQS queue. This JSON message should include a list of the caption files that were created:

```json
{
  "id": "abc123",
  "transcripts": {
    "s3://media/abc123/audio.mp3": [
        "s3://out/abc123/audio.vtt",
        "s3://out/abc123/audio.srt",
        "s3://out/abc123/audio.json"
    ]
  }
}
```

**Comment by jmartin-sul** [comment]
this is done, we just didn't link PR to ticket
