### ISSUE TITLE
Adjust locations for AWS Whisper Container

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/speech-to-text#33]
- docker container should look for files in base bucket and job id folder (where job id is druid-v3 pair), e.g. "s3://sul-speech-to-text-staging/nj873rz3527-v2"
- docker container should place completed files in a subfolder called "out" in the same place the input files came from, e.g. "s3://sul-speech-to-text-staging/nj873rz3527-v2/out"

**Comment by edsu** [comment]
I went with using `output` instead of `out` for the name prefix for result files.
