### ISSUE TITLE
Investigate Whisper.writer parameters

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/speech-to-text#35]
Run different parameter combinations on a media test item and observe the vtt output formatting, attending to subtitle accessibility guidelines and readability.

## Whisper.writer parameters
Subtitle formatting parameters are input to the writer (obtained by whisper.utils.get_writer), and not the model (model.transcribe). NB: To use these writer parameters, `word_timestamps` must be set to True as input to model.transcribe.

- `max_line_width`: the maximum number of characters in a line before breaking the line (default: None)
  - Accessibility guidelines recommend a maximum of 42 characters per line.
- `max_line_count`: the maximum number of lines in a segment (default: None)
  - Accessibility guidelines recommend a maximum of 2 lines per segment.
- `max_words_per_line`: the maximum number of words in a segment (default: None)
  - Line width indeterminate.

Preliminary parameter testing and vtt output: [Pre-pilot parameter testing (Local)](https://docs.google.com/spreadsheets/d/1m2w3nNfQKALdgITWhmyYmFL7f7XOOs60oeozLyLqk-w/edit?usp=sharing).

**Questions**
- `max_words_per_line` may improve readability by breaking caption segments on complete sentences (see the Relevant links below). Should we use this parameter instead of `max_line_width=42` and `max_line_count=2`?
- What happens if all three of the above parameters are specified simultaneously?

## Relevant links

- [Improve default line lengths in subtitle files · openai whisper · Discussion sul-dlss/common-accessioning#314 · GitHub](https://github.com/openai/whisper/discussions/314#discussioncomment-7493101)
- [How to Customize Subtitles with Whisper - CodePull](https://codepull.com/ai/how-to-customize-subtitles-with-whisper/)

**Comment by alundgard** [comment]
This Whisper output contains caption segments that are too long. Although they appear on the screen long enough to read them, accessibility guidelines recommend a max of 42 chars per line, and a max of 2 lines per segment.

https://sul-purl-stage.stanford.edu/jr745nr3367
![Image](https://github.com/user-attachments/assets/8afc71fa-afe3-4775-8ab1-ecae77ab366e)

**Comment by edsu** [comment]
It looks like we the `word_timestamps` option isn't getting set to `True` during transcription when writer options are used which is causing the `max_line_width: 42` option to have no effect. So this appears to be a bug.

**Comment by edsu** [comment]
Interesting, when I turned on `word_timestamps` I saw these warnings in the log:

```
2024-12-03T23:32:56+0000 :: INFO :: running whisper on bp653kn3525-v2/audio_1.m4a with model=large-v3 options={'beam_size': 10, 'word_timestamps': True}
/tmp/tmp_iya3nvf/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/usr/local/lib/python3.11/dist-packages/whisper/timing.py:42: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower median kernel implementation...
  warnings.warn(
/tmp/tmp1swh0cp1/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/usr/local/lib/python3.11/dist-packages/whisper/timing.py:146: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower DTW implementation...
  warnings.warn(
/tmp/tmpl_i_fqxr/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/usr/local/lib/python3.11/dist-packages/whisper/timing.py:42: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower median kernel implementation...
  warnings.warn(
/tmp/tmp4hckhwc0/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/usr/local/lib/python3.11/dist-packages/whisper/timing.py:146: UserWarning: Failed to launch Triton kernels, likely due to missing CUDA toolkit; falling back to a slower DTW implementation...
```

**Comment by edsu** [comment]
Installing python-dev-3.11 seemed to help with the error, and setting word_timestamps during transcription seemed to also fix the writer parameters.

Compare these two transcripts:

before: https://stacks-stage.stanford.edu/file/druid:jq613qs8296/video_1.vtt  
after: https://stacks-stage.stanford.edu/file/druid:jm706vb3065/video_1.vtt

However maybe it still isn't displaying correctly in sul-embed?

https://sul-purl-stage.stanford.edu/jm706vb3065
