### ISSUE TITLE
API docs overview -- how does the file return to us via the Amara API?

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/speech-to-text#37]
RE: Vivian's question post-stand-up today. How does the edited caption/VTT file return to us via the Amara API? 
Here are the Amara API docs: 
https://apidocs.amara.org/

**Comment by peetucket** [comment]
The API docs seem pretty good, and there are clear endpoints for fetching captions for a specific video, namely https://apidocs.amara.org/#fetch-subtitles-data, which returns subtitles in increments by timestamp.  In addition, there is an endpoint that returns the captions for a video in a specific file format, including VTT: https://apidocs.amara.org/#fetch-raw-subtitles

So it's seems straightforward to me how to get captions back for a specific video (and this is the endpoint to list the available videos: https://apidocs.amara.org/#list-videos)
