### ISSUE TITLE
Stanza API docs review

### ISSUE THREAD

**Issue by laurensorensen** [sul-dlss/speech-to-text#38]
Hi, similar to the Amara API docs question in #37 , we need to review how easy / ok an API will work to retrieve edited caption files from the Stanza api documentation. I have it installed locally and unfortunately the API docs are only available within the software (e.g. http://localhost:7000/swagger/index.html). @peetucket offered to do a huddle to review tomorrow 10/24 - if anyone else is available before that I've got time this afternoon too. See slack discussion here for further context: https://stanfordlib.slack.com/archives/C06EVDJV45N/p1729721694280379

**Comment by jmartin-sul** [comment]
API meh, done

**Comment by laurensorensen** [comment]
Here is the back-and-forth I had with Stanza. It could be they misinterpreted what I was saying again, but I can't tell. Bottom is my first message asking them about getting the contents/text of a VTT file versus the actual VTT file. I can follow up if needed. CC: @peetucket @dnoneill 



Lauren,

Yes, this API will download the result of an export:

GET /api/projects/{operationId}/result

Where {operationId} is the Guid of the export operation, which you can get from the export API.



Telestream

Michael Greenstine | Senior Sales Engineer | 661-618-2232 (m)

[Michael.Greenstine@Telestream.net](mailto:Michael.Greenstine@Telestream.net)

From: Lauren Sorensen <lsorens@stanford.edu>
Date: Wednesday, October 30, 2024 at 3:44 PM
To: Michael Greenstine <michael.greenstine@telestream.net>, Justin Henry <Justin.Henry@telestream.net>
Subject: [External Sender] Re: Follow up

Thanks, I think I didn't properly word my question. We understand that we can export VTT files using the API. However, we are wondering if there is a way to get the contents of a caption file using the API -- from what we can see, the tool only allows exporting the VTT file to a location (server or local drive).

 

Thanks,

Lauren

From: Michael Greenstine <michael.greenstine@telestream.net>
Sent: Wednesday, October 30, 2024 3:33 PM
To: Lauren Sorensen <lsorens@stanford.edu>; Justin Henry <Justin.Henry@telestream.net>
Subject: Re: Follow up

 

Lauren,

 

There is an API to export a VTT file from a project, it will write the file to either a local or network drive.

**Comment by dnoneill** [comment]
I would want to know if there is a way to get the results without having to export. Otherwise we still have to export and store the file somewhere.

**Comment by laurensorensen** [comment]
Ok thanks. If direct still wants us to investigate Stanza, I'll see if I can set up a time to meet with them.

**Comment by jmartin-sul** [comment]
open question remains about captions deliverables, @laurensorensen will discuss w/ hannah tomorrow

**Comment by laurensorensen** [comment]
Here is a link to the [new ticket tracking Stanza API testing](https://github.com/sul-dlss/speech-to-text/issues/52). Closing this ticket in place of the new one.
