### ISSUE TITLE
Whisper output quality: test transcription of video where most of speech is German, but opening 30ish seconds of speech is English

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/speech-to-text#47]
@andrewjbtw tested a video like this using the current pipeline, which doesn't yet have UI for specifying language, and so language was auto-detected.  Whisper detected English, presumably because of the opening, and the transcription/translation of the German portion was very poor quality.

@edsu said he can test this pretty easily with the Whisper command line, since we won't necessarily have the language selection UI in place in time to test this before meeting about it on Friday.

The test item Andrew used that switches from English to German: https://sul-purl-stage.stanford.edu/vh170nm3897

**Comment by edsu** [comment]
@andrewjbtw re-ran the english + german media with `language: German` and Whisper seemed to transcribe the introductory English as English and the subsequent German as German. Without `language: German` it seemed to want to transcribe everything as English.
