### ISSUE TITLE
provision S3 buckets and credentials for temp space to hold 1) the incoming content to run through speech-to-text generation, and 2) the generated transcript/caption files.

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/speech-to-text#6]
Ultimately we'll want these defined and provisioned via Terraform, but it's fine to do initial experimentation by manually creating things in AWS web console or using one off `aws` CLI commands.  Whatever feels like the most comfortable path forward is fine (i.e. it's also fine to do it the hard way and try to use Terraform the whole time).  See the guidelines at the top of https://github.com/sul-dlss-labs/sul_media_transcription_services/issues/1

- we want this for stage to start, at least.  we can add prod and QA as we move close to productionizing.
- we probably want to assume we'll use AWS _**via Cardinal Cloud (see ops)**_ for this.
- but as an experiment, try doing this in GCP (same cardinal cloud caveat!), and connecting with the Ruby AWS SDK gem.  The gem should work with any S3 compatible service (we use it with IBM for preservation, and we expect to use it with GCP when we migrate our IBM archived content to GCP next year sometime).

**Comment by edsu** [comment]
I think we want to be doing this in Terraform?

**Comment by edsu** [comment]
I created the stage and dev buckets manually using our sul-developers credentials:

```
aws --profile sul-developers s3 mb s3://sul-speech-to-text-stage
aws --profile sul-developers s3 mb s3://sul-speech-to-text-dev
```

- s3://sul-speech-to-text-stage
- s3://sul-speech-to-text-dev

I think ultimately ops will want to create the production bucket with prod credentials and Terraform.
